stages:
  - build
  - deploy

build:
  stage: build
  image: nixos/nix
  script:
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command bash -c "npm i && npm run build" # TODO: nix build を使えるようにする
  artifacts:
    paths:
      - dist/

generate-menu:
  stage: build
  image: nixos/nix
  script:
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes run .#generate-menu
  artifacts:
    paths:
      - menu.json
  variables:
    CI_DEBUG_TRACE: "true"

pages:
  stage: deploy
  script:
    - true `mv public public~`
    - mv dist public
    - mv menu.json public/menu.json
  artifacts:
    paths:
      - public