stages:
  - build
  - deploy

build:
  stage: build
  image: nixpkgs/nix-flakes:latest
  script:
    - nix develop --command bash -c "npm i && npm run build" # TODO: nix build を使えるようにする
  artifacts:
    paths:
      - dist/

generate-menu:
  stage: build
  image: nixpkgs/nix-flakes:latest
  before_script:
    - nix-shell -p curl libarchive --command "curl -L \"https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/${CI_COMMIT_BRANCH}/download?job=generate-menu\" | bsdtar -x"
  script:
    - nix flakes run .#generate-menu
  artifacts:
    paths:
      - menu.json

pages:
  stage: deploy
  script:
    - true `mv public public~`
    - mv dist public
    - mv menu.json public/menu.json
  artifacts:
    paths:
      - public